language: go

go:
  # - 1.7.x
  - 1.8.x
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -u github.com/go-ego/gse  
  - go get -u github.com/go-ego/gpy 
  - go get -u github.com/go-ego/murmur 
  - go get -u golang.org/x/sys/unix
  - go get -u github.com/shirou/gopsutil
  - go get -v -t

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
# notifications:
#   email:
#     - .com